// Node.js script to embed template source code at build time
const fs = require('fs');
const path = require('path');

const templates = [
  {
    name: 'Outlet Sale Flyer',
    path: 'src/documents/outlet-flyer/OutletFlyer.tsx'
  },
  {
    name: 'Outlet Product Catalog',
    path: 'src/documents/outlet-catalog/OutletCatalog.tsx'
  },
  {
    name: 'Outlet Presentation',
    path: 'src/documents/outlet-presentation/OutletPresentation.tsx'
  },
  {
    name: 'Cactuce Solutions Booklet',
    path: 'src/documents/cactuce-booklet/CactuceBooklet.tsx'
  },
  {
    name: "Plan d'Affaires - The Green Rooftop Parc",
    path: 'src/documents/green-rooftop-business-plan/GreenRooftopBusinessPlan.tsx'
  }
];

function generateSourcesFile() {
  const sources = {};
  
  templates.forEach(template => {
    try {
      const fullPath = path.join(__dirname, '..', template.path);
      const content = fs.readFileSync(fullPath, 'utf8');
      sources[template.name] = content;
    } catch (error) {
      console.error(`Error reading ${template.path}:`, error);
    }
  });
  
  const output = `// This file is auto-generated. Do not edit manually.
// Generated by scripts/embedTemplateSources.js

export const templateSources: Record<string, string> = ${JSON.stringify(sources, null, 2)};

export function getTemplateSource(templateName: string): string | undefined {
  return templateSources[templateName];
}
`;
  
  const outputPath = path.join(__dirname, '..', 'src', 'documents', 'sources.ts');
  fs.writeFileSync(outputPath, output);
  console.log('Template sources embedded successfully!');
}

generateSourcesFile();